name: ZTech Twitter Bot

on:
  schedule:
    # Horarios optimizados para Colombia (GMT-5) y Estados Unidos (GMT-4)
    # 12:00 PM Colombia (5:00 PM UTC) - Mediodía para Latinoamérica
    # 6:00 PM Colombia (11:00 PM UTC) - Fin de jornada para Latinoamérica
    # 9:00 AM Estados Unidos Este (1:00 PM UTC) - Mañana para US
    # 6:00 PM Estados Unidos Este (10:00 PM UTC) - Fin de jornada para US
    - cron: "0 13,17,22,23 * * *"

  # Permitir ejecución manual
  workflow_dispatch:
    inputs:
      post_type:
        description: "Tipo de publicación"
        required: true
        default: "single"
        type: choice
        options:
          - single
          - curated

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configurar variables de entorno
        run: |
          echo "TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }}" >> $GITHUB_ENV
          echo "TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }}" >> $GITHUB_ENV
          echo "TWITTER_BEARER_TOKEN=${{ secrets.TWITTER_BEARER_TOKEN }}" >> $GITHUB_ENV
          echo "TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}" >> $GITHUB_ENV
          echo "NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}" >> $GITHUB_ENV
          echo "REDDIT_CLIENT_ID=${{ secrets.REDDIT_CLIENT_ID }}" >> $GITHUB_ENV
          echo "REDDIT_CLIENT_SECRET=${{ secrets.REDDIT_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "TWITTER_USERNAME=ztech" >> $GITHUB_ENV
          echo "POSTING_SCHEDULE=09:00,18:00" >> $GITHUB_ENV
          echo "TIMEZONE=America/Mexico_City" >> $GITHUB_ENV
          echo "HASHTAGS=#tecnologia #innovacion #AI #programacion" >> $GITHUB_ENV
          echo "MAX_TWEET_LENGTH=280" >> $GITHUB_ENV
          echo "DATABASE_URL=sqlite:///ztech_bot.db" >> $GITHUB_ENV
          echo "LOG_LEVEL=INFO" >> $GITHUB_ENV

      - name: Verificar configuración
        run: python main.py --config-check

      - name: Ejecutar bot
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            python main.py --mode single --post-type ${{ github.event.inputs.post_type }}
          else
            python main.py --mode single --post-type single
          fi

      - name: Subir logs (si hay errores)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: bot-logs
          path: logs/

      - name: Notificar resultado
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ Tweet publicado exitosamente"
          else
            echo "❌ Error en la publicación del tweet"
          fi
